apiVersion: v1
kind: Service
metadata:
  name: wp-mysql
  labels:
    app: wp
spec:
  selector:
    app: wp
    tier: mysql
  ports:
    - port: 3306
  clusterIP: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: wp
spec:
  resources:
    requests:
      storage: 5G
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-mysql
spec:
  selector:
    matchLabels:
      app: wp
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wp
        tier: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: root_pass
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: db_name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: db_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: db_pass
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
